### ISSUE TITLE
Table 'ApiResources' already exists

### ISSUE THREAD

**Issue by benedict1986** [skoruba/IdentityServer4.Admin#103]
Thanks for such a great project.

I have an issue while migrating database.

First of all, I followed the instruction in [EFMigration.md](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md) and [Issue102](https://github.com/skoruba/IdentityServer4.Admin/issues/102) to use MySQL. When I run `Update-Database -context AdminDbContext`, I got

`PM> dotnet ef database update -c AdminDbContext
MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'ApiResources' already exists ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'ApiResources' already exists
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Table 'ApiResources' already exists`

Could you please help to see what did I missed? Thanks

**Comment by skoruba** [comment]
@benedict1986 - Have you tried create a clone of project or via `dotnet new template`?
Thanks!

**Comment by benedict1986** [comment]
Hi skoruba, 

Thanks for such a quick reply. I tried it. But I need to use Skoruba.IdentityServer4.Admin.EntityFramework.DbContexts.dll with the modification mentioned in [Issue102](https://github.com/skoruba/IdentityServer4.Admin/issues/102)

**Comment by skoruba** [comment]
Hi @benedict1986 - I see, you need to create your own DbContext - where you can inherit from original DbContext - but you will override the method - `OnModelCreating` - as is mentioned in #102 
BTW: Please follow these steps for changing DbContext - [steps](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-To-Existing-IS4.md)

I will consider easier approach for MySQL.

**Comment by benedict1986** [comment]
Hi @skoruba ,

Good suggestion. Now I created my own DbContext which inherent from the AdminDbContext and applied it in Startup.cs. However, it does not solve the `Table 'ApiResources' already exists` issue. I ran the migrate commands 

`dotnet ef migrations add DbInit -c AdminDbContext -o Data/Migrations
dotnet ef database update -c AdminDbContext`

But still get the error.  Not sure if we can skip the check for existing table and keep updating. Thanks

**Comment by skoruba** [comment]
Hi @benedict1986 

please, check your database - which migrations were applied - if you are create some changes in model - you can create another migrations - `dotnet ef migrations add ChangeToMySql -c AdminDbContext -o Data/Migrations` - BTW: if you have created your solution via `dotnet new template` - the migrations are part of the solution and were probable applied in first run of application. 

Thanks!

**Comment by skoruba** [comment]
Hi @benedict1986 - you are welcome - if you have any question - please let me know.
Thanks!
