### ISSUE TITLE
Host IdentityServer4.Admin on Azure

### ISSUE THREAD

**Issue by FrankDoersam** [skoruba/IdentityServer4.Admin#108]
Hello,

the project looks really great. How should I do that the service is hosted in Azure?

Yours sincerely
Frank

**Comment by skoruba** [comment]
Hi Frank,
I will prepare the guide - how to create the “production” release. :)
I will contact you.

Thanks!

**Comment by FrankDoersam** [comment]
Hello skoruba,

thank you for the fast feedback. I would really appreciate it if you could show how to fully publish the IdentityService in Azure. I wanted to use this for an Alexa skill :).

Yours sincerely
Frank

**Comment by skoruba** [comment]
Please take a look at: https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-Azure-Deploy.md
Thanks

**Comment by tsangian** [comment]
Hi Skoruba,

I have no problem running on local and then I tried to deploy to Azure App Service using Visual Studio Publish feature. Before deploying I followed the [documentation](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-Azure-Deploy.md), but then it shows "Internal Server Error: An error occurred while starting the application." when I tried to access the STS.Identity UI. Here's the exception from Log table in database (Azure SQL):

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAlwaysRunResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Do you have any idea what causes the error?

The admin UI also returns HTTP 500 error. Only the API runs well since I can access the swagger UI.

Regards,
Tim

**Comment by tsangian** [comment]
Found out the issue. I changed ASPNETCORE_ENVIRONMENT to Development (It was Production) and the error message shows up. Seems like the it can't find the certificate with the thumbprint provided from App Service TLS/SSL settings page. I'm still trying to figure out a solution for this.

Any help appreciated.

**Comment by tsangian** [comment]
Anyone having the same problem with me, you should add an app setting with name `WEBSITE_LOAD_CERTIFICATES` and value `*` to make your certificates accessible from the app.

Reference: https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/

**Comment by alvarovalle** [comment]
Hi, I am having problems even after have been followed the step by step guide 

[here](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-Azure-Deploy.md)

![image](https://user-images.githubusercontent.com/5870264/71730317-99a85b00-2e20-11ea-99ca-12d27c4f4f38.png)

here is my code 

![image](https://user-images.githubusercontent.com/5870264/71730436-e7bd5e80-2e20-11ea-80c0-adbac4f7749b.png)


What do you suggest me to do?

thanks in advance
