### ISSUE TITLE
getting ambiguousactionexception on IDS

### ISSUE THREAD

**Issue by koo9** [skoruba/IdentityServer4.Admin#292]
AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

IdsAdmin.STS.Identity.Controllers.HomeController.Index (IdsAdmin.STS.Identity)
IdsAdmin.Admin.Controllers.HomeController.Index (IdsAdmin.Admin)

for some reason this came up today. it was working fine before. not sure if it's because I updated the nuget packages.

**Comment by skoruba** [comment]
Do you have the references between these projects - AdminUI and STS?

**Comment by koo9** [comment]
yes, been on it for half a day with beyond compare. turns out that when adding new project references to both project, it somehow cause that to happen. if STS add new project referece somecomm.proj then also adding that to AdminUI, the error will happen. I think in the new project structure, this won't happen since you have refactor all the share stuff into their own projects and STS won't have any of the Admin UI controllers. 

btw the latest master branch throws an error when initializing the database.

**Comment by skoruba** [comment]
Which error - can you share the details please?

**Comment by koo9** [comment]
Request matched multiple actions resulting in ambiguity. Matching actions: "IdsAdmin.STS.Identity.Controllers.HomeController.Index (IdsAdmin.STS.Identity)
IdsAdmin.Admin.Controllers.HomeController.Index (IdsAdmin.Admin)"

Request matched multiple actions resulting in ambiguity. Matching actions: {AmbiguousActions}

Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

IdsAdmin.STS.Identity.Controllers.HomeController.Index (IdsAdmin.STS.Identity)
IdsAdmin.Admin.Controllers.HomeController.Index (IdsAdmin.Admin)
   at Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList`1 candidates)
   at Microsoft.AspNetCore.Mvc.Internal.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.Route.OnRouteMatched(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteBase.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\MtlsTokenEndpointMiddleware.cs:line 60
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by koo9** [comment]
think with the new project structure, this error won't happen since IDS won't have reference to admin UI project.

**Comment by skoruba** [comment]
I think we solve this issue on gitter. You should not reference both web projects together.
If you have any another issue, please let me know.
Thanks.

**Comment by koo9** [comment]
no I wasn't referencing both projects. IDs references Idm and if they both references another project, the issue will show

**Comment by skoruba** [comment]
If you want can you please paste .csproj of Admin and STS? I will check it. It sounds weird to me. :)

**Comment by koo9** [comment]
it's easier to create a dummy project say  common.proj and add it to both projects, the issue will show up but this issue won't occur in the new solution structure since IDs does not reference Idm directly anymore

**Comment by skoruba** [comment]
OK, thanks for feedback, I will test it. 👍

**Comment by koo9** [comment]
thanks Skoruba. Great work! 👍👍👍
