### ISSUE TITLE
An exception was thrown while deserializing the token.

### ISSUE THREAD

**Issue by CybrZr00** [skoruba/IdentityServer4.Admin#301]
Hi,

I am having some issues following deployment.  If I attempt to login I get a 500 error. After looking through the logs the only error shown is:

> An exception was thrown while deserializing the token.

> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {6897ac40-a3b0-4169-a339-bc4dd47c10ac} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

I tried removing the token validation, but for some reason still got the error.

I am hosting the 3 projects in subdomains eg: https://identity.domain.com, https://identity-admin.domain.com, and https://admin-api.domain.com which make use of Cloudflare with 'Full Strict' crypto

I haven't been able to figure out what's happening, and was hoping you may be able to point me in the right direction.

I have noticed that the Api is having some ssl issues (error 525), but I hadn't even got that far, so I assume it's nothing to do with the login issue.

**Comment by CybrZr00** [comment]
Oddly enough the issue was with the account controller, I had implemented my own IEmailSender and not updated the using!
