### ISSUE TITLE
No JWKS endpoint (Unable to load PFX file?)

### ISSUE THREAD

**Issue by jordyvaneijk** [skoruba/IdentityServer4.Admin#352]
After moving our identityserver from development to production we cannot sign the JWT tokens using PFX file anymore. We can login but when we try to connect through the admin we get the following exception:

```
2019-08-23 14:38:25.446 +02:00 [FTL] Unhandled exception: No signing credential is configured. Can't create JWT token
System.InvalidOperationException: No signing credential is configured. Can't create JWT token
   at IdentityServer4.Services.DefaultTokenCreationService.CreateHeaderAsync(Token token)
   at IdentityServer4.Services.DefaultTokenCreationService.CreateTokenAsync(Token token)
   at IdentityServer4.Services.DefaultTokenService.CreateSecurityTokenAsync(Token token)
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateImplicitFlowResponseAsync(ValidatedAuthorizeRequest request, String authorizationCode)
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateHybridFlowResponseAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateResponseAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.Endpoints.AuthorizeEndpointBase.ProcessAuthorizeRequestAsync(NameValueCollection parameters, ClaimsPrincipal user, ConsentResponse consent)
   at IdentityServer4.Endpoints.AuthorizeEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

I understand that this exception comes from IdentityServer4 but i was wondering whan can cause this problem. If i change the path to the PFX file to something that doesn't exist it will not start at al, which is good. and i know for sure that the password i'm using is the same as the one used during creating the self signed certificate, because we can import it in the certificate store with this password.

If i take a look at the openid-configuration of our dev environment we see the `jwks` endpoint but on production we do not see it.

Can you please help my identifying the problem. 
Kind Regards,
Jordy

**Comment by aiscrim** [comment]
Take a look into the identity server logs. I guess some error arose when trying to add the signing credentials, so you should see something like "There was an error adding the key file - during the creation of the signing key" and some more details about the error.

**Comment by jordyvaneijk** [comment]
I looked in the logs but saw nothing. After changing the log i could see. it. After some tweaking of the logging i found it. the exact logline was 
`There was an error adding the key file - during the creation of the signing key The system cannot find the file specified` which had to do with the apppool setting `Load User Profile` which was false and needed to be `true`

**Comment by skoruba** [comment]
Thanks for your feedback and @aiscrim for help. 😊
