### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by OverQuartzer** [skoruba/IdentityServer4.Admin#620]
### Describe the bug
Skoruba.IdentityServer4.Admin.Api
/api/PersistedGrants/Subjects
error
### To Reproduce
curl -X GET "http://localhost:4397/api/PersistedGrants/Subjects?page=1&pageSize=10" -H "accept: application/json"

### Relevant parts of the log file

```
<log goes here>
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
PersistedGrantsDto -> PersistedGrantSubjectsApiDto
Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Grant.PersistedGrantsDto -> Skoruba.IdentityServer4.Admin.Api.Dtos.PersistedGrants.PersistedGrantSubjectsApiDto
   at lambda_method(Closure , PersistedGrantsDto , PersistedGrantSubjectsApiDto , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at Skoruba.IdentityServer4.Admin.Api.Mappers.PersistedGrantApiMappers.ToPersistedGrantApiModel[T](Object source) in D:\github\IdentityServer4.Admin\src\Skoruba.IdentityServer4.Admin.Api\Mappers\PersistedGrantApiMappers.cs:line 17
   at Skoruba.IdentityServer4.Admin.Api.Controllers.PersistedGrantsController.Get(String searchText, Int32 page, Int32 pageSize) in D:\github\IdentityServer4.Admin\src\Skoruba.IdentityServer4.Admin.Api\Controllers\PersistedGrantsController.cs:line 31
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IklKVGRzZm02VHBEOGN3X1ZkX05TV1EiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1OTE0MzQzNjUsImV4cCI6MTU5MTQzNzk2NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo0Mzk2IiwiYXVkIjoic2tvcnViYV9pZGVudGl0eV9hZG1pbl9hcGkiLCJjbGllbnRfaWQiOiJza29ydWJhX2lkZW50aXR5X2FkbWluX2FwaV9zd2FnZ2VydWkiLCJzdWIiOiIxNDk2NjBiOS1kMjI1LTRkM2ItOTlkNi03Zjg5NmUzNGU4YWYiLCJhdXRoX3RpbWUiOjE1OTEyMzM1OTMsImlkcCI6ImxvY2FsIiwibmFtZSI6IumCsee7p-e7rSIsInJvbGUiOiJTa29ydWJhSWRlbnRpdHlBZG1pbkFkbWluaXN0cmF0b3IiLCJzY29wZSI6WyJza29ydWJhX2lkZW50aXR5X2FkbWluX2FwaSJdLCJhbXIiOlsicHdkIl19.dXvNuQzHtGgKbhVH8kOi9o_ERjxGyx81KqJAaSH4jWsqbcOhPPOrxVvO8ug9A0lARchsgiM5P27zb87oLUZbLm0y35EGT-LGGhdJqOx8bM66Fcyrq7utpXEFpBCvSHG4Q9P45OsE3fgC7w4AqEw4RB9SNlUWnqIhsh1qZRKkxLAx_JmHAW7kwFQIn6F8AcRcLi8Nry8fU58wyKu73F3zWh6seQjOishPqJejqC7moepPhZawE8Ykk46qRq7ZdBUA82gxWuSdfi6bSvtlqWUS0RmBWhV8aLamfetB_qMklDzWxR0--h4n82_ucOAiCAZlV0RxA55IFP6XbiPSA_vDSg
Cookie: Hm_lvt_d97abf6d61c21d773f97835defbdef4e=1581485922,1583733907; cookieconsent_status=dismiss; Hm_lvt_d214947968792b839fd669a4decaaffc=1588226716; Hm_lvt_bc38887aa5588add05a38704342ad7e8=1589767782; Webstorm-30ebf064=1f8beee3-3a31-4b4d-85dc-dd3023609a1d; .AspNetCore.Culture=c%3Dzh%7Cuic%3Dzh; idsrv.session=yM6Ie6WiCFoETjsMzJ2IDw; .AspNetCore.Identity.Application=CfDJ8K8YeDopa3FJortByjE9Ct7uI4qAvTr2Yvpaytd2_bA1MXLu3XmbHRlrTSX8tlgppJ5DScvbbSsowDTXrD49sHTxJ7scSXeifIfEc9AkGNUB539Ny1whRpiyPf7GX5qxBGlXLc412fB1r_705PVF63XqH7RkJZAggDQk1fHFrhhxvrPHBWHmqVCSMe_WIiyz4ItCE7PAQ1B1f9FH8zc3J75kKnXSWwbmI4j20B0o2ljIoUxFOsbnM3XJatmUzQCKP4e-welDJVcHvGGr0F4PIfApjj4qVGMRynQNVEJvslMxAvRUYO6dT2MW6vCniwbBtc7f1mynu80pTJc-sbEhkRwJaU-sMOGzPIbdy52p5wWraTMJKDtegn8b7A_czSy5VvgKaBzCHkaMWpQW_3kkqJM9BrNpqy51Z5CWi1ocaC-ZAWvkL4rBD89CwFU-0l28QJxW9BBzAj7Opc3dQKWdSL-V3lgYTARW9mT5Yr0We9-B8DlR0MrE-LS037pVInfjdTKBD6KfYJK6y2JNpqToR5gedDJHXvHhdyS6QBz0JnVrX0-st71PCwYUlwZRXE41-VwEYlf21Cf0s8ilCs_fNvRlOyTVsfNNZMNgHhqAaA1ywqf0DXbs_MaTJNzdOatJJXEd7YcIFpIuQprdz4tzSMjQKz_STLYW0lfPzvXCON1N9pRhBvst0cx9RuJaO2XwkoL9XQ4gHHwm2ySW0dPomPQGeoZotKZVz04CQ_rkqGw8U-NzOQZxwY9A09xsrTwUbjavZyf4h5vcreJYqKf9XI80ifwJMwGegCu8JMdWmXjatIR5EKw7uvLU20MaYhU0HuBZAYRz2jRxX9NukcSWKiBEkFs0RbkztKElY1bh--iDCaaXGyM4dlgfCwdC83fNMKMc0jBfx_oW5-EtL71lHlsMXvt6ZxZH7YZG-Y9ktFBerT4E7hIhVilr9VM-_pcrCh8e8UiThQo8gdIAP7SL2mSZ2Le0nV_7KiDOtJeMNVVpS5f626T-JkD9yEyawQmOF3xt59wuiIEsy-xjaHpWZ5AavSBuDVt03JcYQVptZwbOY-y3UsNGELo4gR9FKGgQHjSexXQ3wOXL_mypU9zwj2A; .AspNetCore.Antiforgery.iZkNhJYt2Uc=CfDJ8K8YeDopa3FJortByjE9Ct54sot7TMZG-bxH2FGD2Svzck6N5USssv8GYXUgkDViqRkZsVugy3xDZrGLgYfVS2HugMDeq1euAc2b9ZNvJXUIjDeVegwaB4aZTHhu0Sa9hG_8wquSNUIvSnaGv0jRY74
Host: localhost:4397
Referer: http://localhost:4397/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty

**Comment by skoruba** [comment]
Hi, this is already fixed in the dev branch, I will merge it this month. Thanks for reporting

**Comment by skoruba** [comment]
Fixed in master, thanks 👍🏼
