### ISSUE TITLE
DataProtection in Admin Api

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#638]
### Question
Any reason why the dataprotection db is not registered in Admin API. The Startup helper between Admin and Admin api are slightly different

### Relevant parts of the log file
```[10:23:36 ERR] An error occurred while reading the key ring.
System.InvalidOperationException: No service for type 'Skoruba.IdentityServer4.Admin.EntityFramework.Shared.DbContexts.IdentityServerDataProtectionDbContext' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.EntityFrameworkCoreXmlRepository`1.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)```
```
   <log goes here>
```

**Comment by b0** [comment]
@ekjuanrejon are you on dev branch and latest code?

**Comment by ekjuanrejon** [comment]
yes... i think so

**Comment by b0** [comment]
@ekjuanrejon  Please be sure about that. Code needed for that is only on dev branch and not yet released as nuget packager nor merged to master. Yet...

**Comment by ekjuanrejon** [comment]
https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.Admin.EntityFramework.SqlServer/Extensions/DatabaseExtensions.cs#L55
