### ISSUE TITLE
When multiple users set the same email, editing role information will be wrong

### ISSUE THREAD

**Issue by yomunsam** [skoruba/IdentityServer4.Admin#640]
### Describe the bug
When multiple users set the same email, editing role information will throw an exception.

### To Reproduce

When multiple users set the same email
![image](https://user-images.githubusercontent.com/24813704/85496627-351bcb00-b60f-11ea-8176-9f307120ee3e.png)

Add role to one of the users
![image](https://user-images.githubusercontent.com/24813704/85496696-55e42080-b60f-11ea-904a-87f7e00695a3.png)

![image](https://user-images.githubusercontent.com/24813704/85496787-7613df80-b60f-11ea-8f4c-c3dc47f6d121.png)

![image](https://user-images.githubusercontent.com/24813704/85496802-7e6c1a80-b60f-11ea-8d6e-c6f917f167cf.png)

This situation seems to be caused by the use of email information to query users within the framework

------

After thinking about it, we found that in the admin panel, we can't set up two roles of the same email, but in the STS.Identity In, we can change our email information to an existing email

### Relevant parts of the log file

System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateEmail(UserManager`1 manager, TUser user, List`1 errors)
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.AddToRoleAsync(TUser user, String role)
   at Skoruba.IdentityServer4.Admin.EntityFramework.Identity.Repositories.IdentityRepository`11.CreateUserRoleAsync(String userId, String roleId)
   at Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Services.IdentityService`22.CreateUserRoleAsync(TUserRolesDto role)
   at CPDIS.IdentityServer.Admin.Controllers.IdentityController`22.UserRoles(TUserRolesDto role) in E:\DevWork\OutSource\CPDIS\CPDIS.IdentityServer\src\CPDIS.IdentityServer.Admin\Controllers\IdentityController.cs:line 195
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by skoruba** [comment]
I will check it, thanks for reporting.

What is your configuration of identity? Do you use for login username or email? Do you configure possibility register same email twice?

**Comment by yomunsam** [comment]
![image](https://user-images.githubusercontent.com/24813704/85499064-7b732900-b613-11ea-9128-f0c6d5a1cc6a.png)

Use username.

And I  modified the settings of StartupHelpers, will it be related to this?

![image](https://user-images.githubusercontent.com/24813704/85499316-ee7c9f80-b613-11ea-9f84-22db6416657a.png)

**Comment by skoruba** [comment]
I will test it, thanks for your setup 👍🏼

**Comment by vicentt** [comment]
The problem is having multiple places where you can edit users with conflicting settings.

In the STS project you have

`
 services.AddIdentity <TUserIdentity, TUserIdentityRole> (options =>
                {
                    options.User.RequireUniqueEmail = false;
                })
`

However in the Admin and Api project you can have

`
  services.AddIdentity <TUser, TRole> (options => {options.User.RequireUniqueEmail = true;})
`

This line causes that the EmailValidator try to pass when UpdateUserAsync is executed
Having two users with the same email

This validator crash on this line:
``
Users.Where (u => u.NormalizedEmail == normalizedEmail) .SingleOrDefault ()
``

The SingleOrDefault throws the ThrowMoreThanOneElementException.

In addition to throwing an error message instead of the DeveloperException and error 500, little can be done as user creation and validation policies and settings must be consistent between the IdentityServer instance and the Administration project.

To solve it in this project, perhaps it could take that value from a common place.  Any ideas?

In the case of using  the Admin project with an IdentityServer that is already in production, its mandatory to analyze the characteristics and restrictions of the IS to use it in the Admin project.

Bye!

**Comment by skoruba** [comment]
@vicentt - thanks for you feedback regarding this issue - I will go through all app and test it.
