### ISSUE TITLE
Cannot update claims with admin api

### ISSUE THREAD

**Issue by JayJay1989** [skoruba/IdentityServer4.Admin#815]
### Describe the bug
[This action](https://github.com/skoruba/IdentityServer4.Admin/blob/release/2.0.0/src/Skoruba.IdentityServer4.Admin.Api/Controllers/UsersController.cs#L182) & [this action](https://github.com/skoruba/IdentityServer4.Admin/blob/release/2.0.0/src/Skoruba.IdentityServer4.Admin.Api/Controllers/UsersController.cs#L197) are both checking if the id is a 0 before it executes the query. But: an update requires the id to be exactly the one in the database, so the `PUT` action crashes becuase it needs to be 0.

### To Reproduce

```sh
curl -X PUT "https://localhost:6001/api/Users/Claims" -H  "accept: */*" -H  "Authorization: Bearer ...." -H  "Content-Type: application/json" -d "{\"claimId\":0,\"userId\":\"ca4f7c98-6e2f-4b50-b99c-2a2552225577\",\"claimType\":\"picture\",\"claimValue\":\"/my/url/to/the/picture.png\"}"
```

### Relevant parts of the log file

```
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Skoruba.IdentityServer4.Admin.EntityFramework.Identity.Repositories.IdentityRepository`9.UpdateUserClaimsAsync(TUserClaim claims)
   at Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Services.IdentityService`20.UpdateUserClaimsAsync(TUserClaimsDto claimsDto)
   at Scoops.Identity.Admin.Api.Controllers.UsersController`20.PutUserClaims(UserClaimApiDto`1 claim) in C:\Users\jonas.lateur\Desktop\ScoopsV2\src\Scoops.Identity.Admin.Api\Controllers\UsersController.cs:line 239
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Possible fix:
removal of following code from the put action
```cs
            if (!userClaimDto.ClaimId.Equals(default))
            {
                return BadRequest(_errorResources.CannotSetId());
            }
```

**Comment by skoruba** [comment]
I will check it, thanks!
