### ISSUE TITLE
Authorization failed. "These requirements were not met:\nRolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Admin)"

### ISSUE THREAD

**Issue by senzacionale** [skoruba/IdentityServer4.Admin#944]
I am getting this error in Docker and I don't know what can I do or how to solve it?

```
[2022-01-01T04:20:17.1797795+00:00][INFO][15][Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed. "These requirements were not met:\nRolesAuthorizationRequirement:User.IsInRole must be true for one of the following roles: (Admin)"
[2022-01-01T04:20:17.1837170+00:00][EROR][17][Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
 ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'System.String'.
 ---> System.Net.Http.HttpRequestException: Connection refused (sts.tcgzone.com:443)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by skoruba** [comment]
Can you please share your docker compose? 
thanks

**Comment by senzacionale** [comment]
Hi, sure:

docker-compose.yml

`version: '3.4'
services:  
  multistoreidentity.admin:
    image: '${DOCKER_REGISTRY-}multistore-identityserver4-admin'
    build:
      context: .
      dockerfile: src/MultiStoreIdentity.Admin/Dockerfile
    container_name: multistore-identityserver4-admin
    environment:
      - VIRTUAL_HOST=admin.multistore.local
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=admin.multistore.local
      - LETSENCRYPT_EMAIL=admin@multistore.local
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.multistore.local'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://admin.multistore.local/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://sts.multistore.local'
      - AdminConfiguration__RequireHttpsMetadata=false
      - 'IdentityServerData__Clients__0__ClientUri=https://admin.multistore.local'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://admin.multistore.local/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.multistore.local/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.multistore.local/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.multistore.local'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://admin-api.multistore.local/swagger/oauth2-redirect.html'
      - 'Serilog__WriteTo__1__Args__connectionString=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    command: dotnet MultiStoreIdentity.Admin.dll /seed
      - multistoreidentity.sts.identity
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/identitydata.json:/app/identitydata.json'
      - './shared/identityserverdata.json:/app/identityserverdata.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui: null
      nginx-network: null
      postgres-network: null
    restart: always

  multistoreidentity.admin.api:
    image: '${DOCKER_REGISTRY-}multistore-identityserver4-admin-api'
    build:
      context: .
      dockerfile: src/MultiStoreIdentity.Admin.Api/Dockerfile
    container_name: multistore-identityserver4-admin-api
    environment:
      - VIRTUAL_HOST=admin-api.multistore.local
      - AdminApiConfiguration__RequireHttpsMetadata=false
      - 'AdminApiConfiguration__ApiBaseUrl=https://admin-api.multistore.local'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://sts.multistore.local'
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui: null
      nginx-network: null
      postgres-network: null
    restart: always

  multistoreidentity.sts.identity:
    image: '${DOCKER_REGISTRY-}multistore-identityserver4-sts-identity'
    build:
      context: .
      dockerfile: src/MultiStoreIdentity.STS.Identity/Dockerfile
    container_name: multistore-identityserver4-sts-identity
    environment:
      - VIRTUAL_HOST=sts.multistore.local
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.multistore.local'
      - 'AdvancedConfiguration__PublicOrigin=https://sts.multistore.local'
      - 'AdvancedConfiguration__IssuerUri=https://sts.multistore.local'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - './shared/serilog.json:/app/serilog.json'
      - './shared/nginx/certs/cacerts.crt:/usr/local/share/ca-certificates/cacerts.crt'
    networks:
      identityserverui: null
      nginx-network:
        aliases:
          - sts.multistore.local      
      postgres-network: null
    restart: always

volumes:
  dbdata:
    driver: local

networks:
  identityserverui:
    driver: bridge
  nginx-network:
    external:    
      name: nginx-network
  postgres-network:
    external:    
      name: postgres-network
`

Override.yml

`version: '3.4'

services:
  multistoreidentity.admin:
    environment:
      - VIRTUAL_HOST=admin.tcgzone.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=admin.tcgzone.com
      - LETSENCRYPT_EMAIL=info@tcgzone.com
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.tcgzone.com'
      - 'AdminConfiguration__IdentityAdminRedirectUri=https://admin.tcgzone.com/signin-oidc'
      - 'AdminConfiguration__IdentityServerBaseUrl=https://sts.tcgzone.com'
      - 'AdminConfiguration__RequireHttpsMetadata=false'
      - 'IdentityServerData__Clients__0__ClientUri=https://admin.tcgzone.com'
      - 'IdentityServerData__Clients__0__RedirectUris__0=https://admin.tcgzone.com/signin-oidc'
      - 'IdentityServerData__Clients__0__FrontChannelLogoutUri=https://admin.tcgzone.com/signin-oidc'
      - 'IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://admin.tcgzone.com/signout-callback-oidc'
      - 'IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://admin.tcgzone.com'
      - 'IdentityServerData__Clients__1__RedirectUris__0=https://admin-api.tcgzone.com/swagger/oauth2-redirect.html'
      - 'IdentityServerData__Clients__1__AllowedCorsOrigins__0=https://admin-api.tcgzone.com'
      - 'IdentityServerData__Clients__2__RedirectUris__0=https://localhost:4200/auth-callback'
      - 'IdentityServerData__Clients__2__RedirectUris__1=https://127.0.0.1:4200/auth-callback'
      - 'IdentityServerData__Clients__2__RedirectUris__2=https://tcgzone.com/auth-callback'
      - 'IdentityServerData__Clients__2__RedirectUris__3=https://www.tcgzone.com/auth-callback'
      - 'IdentityServerData__Clients__2__PostLogoutRedirectUris__0=https://localhost:4200/'
      - 'IdentityServerData__Clients__2__PostLogoutRedirectUris__1=https://127.0.0.1:4200/'
      - 'IdentityServerData__Clients__2__PostLogoutRedirectUris__2=https://tcgzone.com/'
      - 'IdentityServerData__Clients__2__PostLogoutRedirectUris__3=https://www.tcgzone.com/'
      - 'IdentityServerData__Clients__2__AllowedCorsOrigins__0=https://localhost:4200'
      - 'IdentityServerData__Clients__2__AllowedCorsOrigins__1=https://127.0.0.1:4200'
      - 'IdentityServerData__Clients__2__AllowedCorsOrigins__2=https://tcgzone.com'
      - 'IdentityServerData__Clients__2__AllowedCorsOrigins__3=https://www.tcgzone.com'
      - 'Serilog__WriteTo__1__Args__connectionString=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  multistoreidentity.admin.api:
    environment:
      - VIRTUAL_HOST=admin-api.tcgzone.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=admin-api.tcgzone.com
      - LETSENCRYPT_EMAIL=info@tcgzone.com
      - AdminApiConfiguration__RequireHttpsMetadata=true
      - 'AdminApiConfiguration__ApiBaseUrl=https://admin-api.tcgzone.com'
      - 'AdminApiConfiguration__IdentityServerBaseUrl=https://sts.tcgzone.com'
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__AdminAuditLogDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  multistoreidentity.sts.identity:
    environment:
      - VIRTUAL_HOST=sts.tcgzone.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sts.tcgzone.com
      - LETSENCRYPT_EMAIL=info@tcgzone.com
      - 'ConnectionStrings__ConfigurationDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__PersistedGrantDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__IdentityDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'ConnectionStrings__DataProtectionDbConnection=Server=postgres; User Id=identity_server; Database=identity_server; Port=5432; Password=${DB_PASSWORD:-identity_server!6789}; SSL Mode=Prefer; Trust Server Certificate=true'
      - 'AdminConfiguration__IdentityAdminBaseUrl=https://admin.tcgzone.com'
      - 'AdvancedConfiguration__PublicOrigin=https://sts.tcgzone.com'
      - 'AdvancedConfiguration__IssuerUri=https://sts.tcgzone.com'
      - DockerConfiguration__UpdateCaCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    networks:
      identityserverui: null
      nginx-network:
        aliases:
          - sts.tcgzone.com     
      postgres-network: null
`

**Comment by skoruba** [comment]
I faced same issue and I had to add alias sts.tcgzone.com into nginx container as well.
what do you think?

**Comment by senzacionale** [comment]
Hi. Hmm same error:

```
[2022-01-02T16:19:03.0053453+00:00][EROR][15][Microsoft.AspNetCore.Server.Kestrel] Connection id ""0HMEE1EB2GAON"", Request id ""0HMEE1EB2GAON:00000002"": An unhandled exception was thrown by the application.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by senzacionale** [comment]
I will close this issue. It is fixed. Thank you!

**Comment by apetrut** [comment]
@senzacionale Do you still get this error after setting aliases?
User.IsInRole must be true for one of the following roles: (Admin)" ?

**Comment by senzacionale** [comment]
No. Working for me
