### ISSUE TITLE
IIS Deployment - No response from Identity Server 

### ISSUE THREAD

**Issue by OwenManx** [skoruba/IdentityServer4.Admin#945]
Hey there, 

I'm trying to debug an issue with an IIS deployment and I'm struggling to find any relevant documentation. 

**Brief background** 
I've generated the relevant project files - https://github.com/skoruba/IdentityServer4.Admin#create-new-project 
It is all working locally in development. I've then deployed the Skoruba.IdentityServer4.STS.Identity project & Skoruba.IdentityServer4.Admin project.

I can log directly into the identity server and it all appears to work fine until..

**The issue**
Once the admin site tries to redirect to the identity server, the browser does not get a response. It doesn't seem to even timeout, it just sits there with a spinning wheel. 

I know the admin site is there because I can go to a page that doesn't require authorization. I have additionally deployed another site which doesn't connect either.

**In Event Viewer on the server I get this exception:** 

```

Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
RequestPath: /Account/Test

An unhandled exception has occurred while executing the request.

Exception: 
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

Any help / thoughts much appreciated. 

**Edit 1:** 
I've created a new web app and tried linking to the authentication server - it's become apparent that no error messages are being shown after deployment e.g. "unauthorized_client" (I purposefully didn't set up a client in the database). Any ideas as to why this would be? They work when the site is run locally connecting to the deployed authentication server.

The authentication server is configured to show them? 

```

`                   options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;`
```

Cheers

**Comment by OwenManx** [comment]
I've managed to fix this by restarting the server. (Standard!)

I can only assume it was something to do with installing the .NET 5 runtime on a brand new server? The identity server wasn't responding to requests from external sites. 

I'll close the question anyway.

Cheers

**Comment by skoruba** [comment]
Hello, thank you for letting me know. 🙂
